language: node_js

node_js:
  - "8"

services: mongodb

branches:
  only:
  - master

env:
  - TEST_DIR=tilt-client
  - TEST_DIR=tilt-server

cache:
  directories:
    - "node_modules"
    - "./client/node_modules"
  yarn: true

script: cd $TEST_DIR && yarn install && yarn test

after_success:
	- ./node_modules/coveralls/bin/coveralls.js
