language: node_js

node_js:
  - "8"

services: mongodb

branches:
  only:
  - master

cache:
  directories:
    - "node_modules"
  yarn: true

before_script:
	- yarn
	- cd client
	- yarn

after_success:
	- ./node_modules/coveralls/bin/coveralls.js
