language: node_js

node_js: "8"

services: mongodb

branches:
  only:
  - master


cache:
  directories:
    - "node_modules"
    - "./client/node_modules"
  yarn: true

after_success: yarn add coveralls && cat ./coverage/lcov.info | coveralls
