language: node_js

node_js: "8"

services: mongodb

branches:
  only:
  - master

env:
  - TEST_DIR=client
  - TEST_DIR=./

cache:
  directories:
    - "node_modules"
    - "./client/node_modules"
  yarn: true

script: cd $TEST_DIR && yarn install && yarn test

after_success: yarn add coveralls && cat ./coverage/lcov.info | coveralls
